### ISSUE TITLE
Errors in predict.ossl function

### ISSUE THREAD

**Issue by ghost** [soilspectroscopy/ossl-models#1]
I have encountered an issue while trying to execute the predict.ossl function. In the OSSL_functions.R file, errors are being returned in rows 347, 360, 371, and 398 due to missing slashes between 'models.dir' and 'target', as well as a missing 'target' in row 347. Additionally, row 356 produces the following error: 'Error in predict.prcomp(pca.model, data.prep) : 'newdata' does not have the correct number of columns.

**Comment by zecojls** [comment]
Hi @ivdanilin are you still getting the error? Could you please share a reproducible example? Thx

**Comment by ghost** [comment]
Greetings! Here I use the R project from ossl-models-main repository (https://github.com/soilspectroscopy/ossl-models) and the example code provided in [060-prediction_models.Rmd](https://github.com/soilspectroscopy/ossl-manual/blob/main/060-prediction_models.Rmd)

library("tidyverse")
library("mlr3")
library("qs")
library("asdreader")
library("opusreader2")
library("matrixStats")

source("R-mlr/OSSL_functions.R")

list.files("sample-data")

clay.visnir.ossl <- predict.ossl(target = "clay.tot_usda.a334_w.pct",
                                 spectra.file = "sample-data/101453MD01.asd",
                                 spectra.type = "visnir",
                                 subset.type = "ossl",
                                 geo.type = "na",
                                 models.dir = "~/mnt-ossl/ossl_models/")

Error output:

Error in qs::qread(paste0(models.dir, "pca.ossl/mpca_", spectra.type,  : 
  Failed to open file for reading. 
- Does the file exist?
 - Do you have file permissions?
- Is the file name long? (usually 255 chars)

**Comment by zecojls** [comment]
Hi Igor, thanks for providing more info. It looks like you haven't downloaded the models to your computer, so you will need them.

Alternatively, you can get predictions using our web application called [OSSL Explorer](https://engine.soilspectroscopy.org/). Just make sure to upload a CSV file or an OPUS/ASD file within the specified ranges: 400-2500 nm for VisNIR, 600-4000 cm<sup>-1</sup> for MIR, and 1350-2550 for NIR (Neospectra).

Otherwise, follow this if you are interested in running  the models directly on your computer:

1. Download all the remote files using [script_04f_download_ossl_models.R](https://github.com/soilspectroscopy/ossl-models/blob/main/R-mlr/script_04f_download_ossl_models.R).
2. Make sure to have a copy of the [R-mlr/OSSL_functions.R](https://github.com/soilspectroscopy/ossl-models/blob/main/R-mlr/OSSL_functions.R), or better, download/pull this GitHub repository to your computer which includes everything (functions and example datasets).
3. Set the working directory in R so that `R-mlr/OSSL_functions.R` and `sample-data` are properly referenced.
4. Run the same code snippet by providing the correct path of the ossl_models where you downloaded all the files, e.g. `~/projects/temp/ossl_models/`:

```r
library("tidyverse")
library("mlr3")
library("qs")
library("asdreader")
library("opusreader2")
library("matrixStats")

source("R-mlr/OSSL_functions.R")

list.files("sample-data")

clay.visnir.ossl <- predict.ossl(target = "clay.tot_usda.a334_w.pct",
                                 spectra.file = "sample-data/101453MD01.asd",
                                 spectra.type = "visnir",
                                 subset.type = "ossl",
                                 geo.type = "na",
                                 models.dir = "~/projects/temp/ossl_models/")
```

**Comment by ghost** [comment]
Greetings! Thank you for providing the recommendations on the issue. The web application works well. The problem with the R script was not only in the aforementioned typos but also in the fact that after downloading the models, PCA data (in the "pca.ossl" folder) is only available for the "nir.neospectra" variant.
